# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#   schedule:
#     - cron: '30 10 * * 1'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: save secrets to files
      run: |
        echo "$EMAIL_ACCESS_KEY_ID" >> /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools/credentials/email_access_key_id.txt
        echo "$SECRET_ACCESS_KEY" >> /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools/credentials/email_secret_access_key.secret
        echo "$ESPN_S2" >> /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools/credentials/espn_s2.secret
        echo "$SWID" >> /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools/credentials/swid.secret
        echo "$LEAGUE_ID" >> /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools/credentials/league_id.txt
      shell: bash
      env:
        EMAIL_ACCESS_KEY_ID: ${{secrets.email_access_key_id}}
        SECRET_ACCESS_KEY: ${{secrets.email_secret_access_key}}
        ESPN_S2: ${{secrets.espn_s2}}
        SWID: ${{secrets.swid}}
        LEAGUE_ID: ${{secrets.league_id}}
    - name: Test with pytest
      run: |
        pytest
    - name: Predict this week
      run: python predict/predict_week.py
      env:
        PYTHONPATH: /home/runner/work/fantasy_basketball_tools/fantasy_basketball_tools
